[profile.default]
solc_version = "0.8.24"
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@openzeppelin-v5/=lib/openzeppelin-contracts/",
    "@superfluid-finance/=lib/superfluid-protocol-monorepo/packages"
]

# Lint configuration
[lint]
ignore = ["test/**/*.sol"]